### ISSUE TITLE
Store selected items in list view

### ISSUE THREAD

**Issue by ovnicraft** [LLluma/ea_web#2]
Hello, i want to know if you do any work around in this case:

When you add records in m2m field select window launched allow select records but if you search selected items are lost.
This is so complicated with more than 80 records and need search in this view.

Regards,

**Comment by ghost** [comment]
Hi Cristian,
this is in the pipeline. now we are very busy with some hard deadlines to meet by the end of the month, but as soon as we clear up, will push a new update to the ea-web. tons of fixes and enhancements. stay tuned.

**Comment by ovnicraft** [comment]
Thanks for your answer !
